In [1]:
import pandas as pd

In [4]:
df_sin_full = pd.read_csv('checkpoint_paysim_Dlatent_I_sin_full/metrics.csv')
df = pd.read_csv('checkpoint_paysim_Dlatent_I/metrics.csv')

In [8]:
df_solo_full = df.loc[df['method'] == 'Full-data']
df_solo_full.head(10)

,model,method,cv_balanced,cv_macro_f1,cv_weighted_f1,cv_accuracy,cv_balanced_std,cv_macro_f1_std,cv_weighted_f1_std,cv_accuracy_std,...,test_roc_auc,inf_time_per_sample,space,IPC,seed,vae_pretrain_time,vae_fine_tunning_time,encoder_inference_time,decoder_inference_time,destillation_time
0,naive_bayes,Full-data,0.783,0.364,0.722,0.567,0.000,0.001,0.001,0.002,...,NaN,0.000000,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,logreg,Full-data,0.718,0.792,0.999,0.999,0.015,0.013,0.000,0.000,...,NaN,0.000000,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,knn,Full-data,0.847,0.902,1.000,1.000,0.003,0.003,0.000,0.000,...,NaN,0.000543,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,xgb,Full-data,0.925,0.942,1.000,1.000,0.004,0.004,0.000,0.000,...,NaN,0.000000,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,rf,Full-data,0.988,0.598,0.994,0.990,0.002,0.003,0.000,0.000,...,NaN,0.000016,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,mlp,Full-data,0.855,0.908,1.000,1.000,0.013,0.004,0.000,0.000,...,NaN,0.000001,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_sin_full_complete = pd.concat([df_solo_full, df_sin_full], axis=0)
df_sin_full_complete.head(20)

,model,method,cv_balanced,cv_macro_f1,cv_weighted_f1,cv_accuracy,cv_balanced_std,cv_macro_f1_std,cv_weighted_f1_std,cv_accuracy_std,...,test_roc_auc,inf_time_per_sample,space,IPC,seed,vae_pretrain_time,vae_fine_tunning_time,encoder_inference_time,decoder_inference_time,destillation_time
0,naive_bayes,Full-data,0.783,0.364,0.722,0.567,0.000,0.001,0.001,0.002,...,NaN,0.000000,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,logreg,Full-data,0.718,0.792,0.999,0.999,0.015,0.013,0.000,0.000,...,NaN,0.000000,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,knn,Full-data,0.847,0.902,1.000,1.000,0.003,0.003,0.000,0.000,...,NaN,0.000543,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,xgb,Full-data,0.925,0.942,1.000,1.000,0.004,0.004,0.000,0.000,...,NaN,0.000000,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,rf,Full-data,0.988,0.598,0.994,0.990,0.002,0.003,0.000,0.000,...,NaN,0.000016,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,mlp,Full-data,0.855,0.908,1.000,1.000,0.013,0.004,0.000,0.000,...,NaN,0.000001,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,naive_bayes,random,0.800,0.760,0.760,0.800,0.187,0.244,0.244,0.187,...,NaN,0.000000,original,10.0,5.0,NaN,NaN,NaN,NaN,NaN
1,logreg,random,0.800,0.733,0.733,0.800,0.245,0.327,0.327,0.245,...,NaN,0.000000,original,10.0,5.0,NaN,NaN,NaN,NaN,NaN
2,knn,random,0.750,0.680,0.680,0.750,0.224,0.299,0.299,0.224,...,NaN,0.000001,original,10.0,5.0,NaN,NaN,NaN,NaN,NaN
3,xgb,random,0.900,0.867,0.867,0.900,0.200,0.267,0.267,0.200,...,NaN,0.000000,original,10.0,5.0,NaN,NaN,NaN,NaN,NaN
4,rf,random,0.750,0.707,0.707,0.750,0.158,0.213,0.213,0.158,...,NaN,0.000004,original,10.0,5.0,NaN,NaN,NaN,NaN,NaN
5,mlp,random,0.700,0.627,0.627,0.700,0.187,0.259,0.259,0.187,...,NaN,0.000000,original,10.0,5.0,NaN,NaN,NaN,NaN,NaN
6,naive_bayes,k-means,0.700,0.600,0.600,0.700,0.245,0.327,0.327,0.245,...,NaN,0.000000,original,10.0,5.0,2907.08621,0.0,8.562815e-07,0.001395,16.823166
7,logreg,k-means,0.750,0.713,0.713,0.750,0.224,0.266,0.266,0.224,...,NaN,0.000000,original,10.0,5.0,2907.08621,0.0,8.562815e-07,0.001395,16.823166
8,knn,k-means,0.750,0.680,0.680,0.750,0.224,0.299,0.299,0.224,...,NaN,0.000001,original,10.0,5.0,2907.08621,0.0,8.562815e-07,0.001395,16.823166
9,xgb,k-means,0.850,0.813,0.813,0.850,0.200,0.261,0.261,0.200,...,NaN,0.000000,original,10.0,5.0,2907.08621,0.0,8.562815e-07,0.001395,16.823166
10,rf,k-means,0.700,0.693,0.693,0.700,0.187,0.185,0.185,0.187,...,NaN,0.000003,original,10.0,5.0,2907.08621,0.0,8.562815e-07,0.001395,16.823166
11,mlp,k-means,0.550,0.473,0.473,0.550,0.245,0.280,0.280,0.245,...,NaN,0.000000,original,10.0,5.0,2907.08621,0.0,8.562815e-07,0.001395,16.823166
12,naive_bayes,k-means,0.550,0.520,0.520,0.550,0.245,0.261,0.261,0.245,...,NaN,0.000001,latent,10.0,5.0,2907.08621,0.0,8.562815e-07,0.001395,16.823166
13,logreg,k-means,0.800,0.787,0.787,0.800,0.292,0.311,0.311,0.292,...,NaN,0.000000,latent,10.0,5.0,2907.08621,0.0,8.562815e-07,0.001395,16.823166

In [12]:
df_sin_full_complete.to_csv('checkpoint_paysim_Dlatent_I/metrics.csv',index=False)